{application,devo,
             [{description,"SD Erlang online Profiling and Visualisation ."},
              {vsn,"1"},
              {modules,[dbg,devo,devo_app,devo_sampling,devo_sup,
                        devo_toppage_handler,devo_trace,devo_ws_handler,
                        icircles_caller,java_app]},
              {registered,[]},
              {applications,[kernel,stdlib,cowboy]},
              {mod,{devo_app,[]}},
              {env,[]}]}.
